#############################################################################
# Makefile for building: NewsReader.app/Contents/MacOS/NewsReader
# Generated by qmake (3.1) (Qt 5.15.0)
# Project:  NewsReader.pro
# Template: app
# Command: /Volumes/Media/Qt/5.15.0/clang_64/bin/qmake -o Makefile NewsReader.pro -config release
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WEBENGINE_LIB -DQT_WEBENGINECORE_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_WEBCHANNEL_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_POSITIONING_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -I../../../Media/Qt/5.15.0/clang_64/lib/QtWebEngine.framework/Headers -I../../../Media/Qt/5.15.0/clang_64/lib/QtWebEngineCore.framework/Headers -I../../../Media/Qt/5.15.0/clang_64/lib/QtQuick.framework/Headers -I../../../Media/Qt/5.15.0/clang_64/lib/QtGui.framework/Headers -I../../../Media/Qt/5.15.0/clang_64/lib/QtQmlModels.framework/Headers -I../../../Media/Qt/5.15.0/clang_64/lib/QtWebChannel.framework/Headers -I../../../Media/Qt/5.15.0/clang_64/lib/QtQml.framework/Headers -I../../../Media/Qt/5.15.0/clang_64/lib/QtNetwork.framework/Headers -I../../../Media/Qt/5.15.0/clang_64/lib/QtPositioning.framework/Headers -I../../../Media/Qt/5.15.0/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../Media/Qt/5.15.0/clang_64/mkspecs/macx-clang -F/Volumes/Media/Qt/5.15.0/clang_64/lib
QMAKE         = /Volumes/Media/Qt/5.15.0/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Volumes/Media/Qt/5.15.0/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Volumes/Media/Qt/5.15.0/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = NewsReader1.0.0
DISTDIR = /Volumes/Projects/GitHub/NewsReader/.tmp/NewsReader1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Volumes/Media/Qt/5.15.0/clang_64/lib
LIBS          = $(SUBLIBS) -F/Volumes/Media/Qt/5.15.0/clang_64/lib -framework QtWebEngine -framework QtWebEngineCore -framework QtQuick -framework QtGui -framework AppKit -framework Metal -framework QtQmlModels -framework QtWebChannel -framework QtQml -framework QtNetwork -framework QtPositioning -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		news.cpp qrc_qml.cpp \
		qrc_documentation.cpp \
		qrc_images.cpp \
		moc_news.cpp
OBJECTS       = main.o \
		news.o \
		qrc_qml.o \
		qrc_documentation.o \
		qrc_images.o \
		moc_news.o
DIST          = icofont/demo.html \
		icofont/fonts/icofont.eot \
		icofont/fonts/icofont.svg \
		icofont/fonts/icofont.ttf \
		icofont/fonts/icofont.woff \
		icofont/fonts/icofont.woff2 \
		icofont/icofont.css \
		icofont/icofont.min.css \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/spec_pre.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/qdevice.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/device_config.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/common/unix.conf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/common/mac.conf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/common/macx.conf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/common/sanitize.conf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/common/gcc-base.conf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/common/clang.conf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/common/clang-mac.conf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/qconfig.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_pdf.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_pdf_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_pdfwidgets.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3d.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3drender.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3drender_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/qt_functions.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/qt_config.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/toolchain.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/default_pre.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/resolve_config.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/default_post.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/mac/mac.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/warn_on.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/qt.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/resources_functions.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/resources.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/moc.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/unix/thread.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/qmake_use.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/file_copies.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/mac/rez.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/exceptions.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/yacc.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/lex.prf \
		NewsReader.pro news.h main.cpp \
		news.cpp
QMAKE_TARGET  = NewsReader
DESTDIR       = 
TARGET        = NewsReader.app/Contents/MacOS/NewsReader

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.15.6
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Volumes/Projects/GitHub/NewsReader/NewsReader.pro


include /Volumes/Media/Qt/5.15.0/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

NewsReader.app/Contents/MacOS/NewsReader:  $(OBJECTS)  
	@test -d NewsReader.app/Contents/MacOS/ || mkdir -p NewsReader.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: NewsReader.pro ../../../Media/Qt/5.15.0/clang_64/mkspecs/macx-clang/qmake.conf ../../../Media/Qt/5.15.0/clang_64/mkspecs/features/spec_pre.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/qdevice.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/device_config.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/common/unix.conf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/common/mac.conf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/common/macx.conf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/common/sanitize.conf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/common/gcc-base.conf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/common/clang.conf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/common/clang-mac.conf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/qconfig.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_pdf.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_pdf_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_pdfwidgets.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3d.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3drender.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3drender_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/qt_functions.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/qt_config.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/toolchain.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/default_pre.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/resolve_config.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/default_post.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/mac/mac.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/warn_on.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/qt.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/resources_functions.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/resources.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/moc.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/unix/thread.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/qmake_use.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/file_copies.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/mac/rez.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/exceptions.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/yacc.prf \
		../../../Media/Qt/5.15.0/clang_64/mkspecs/features/lex.prf \
		NewsReader.pro \
		qml.qrc \
		documentation.qrc \
		images.qrc \
		../../../Media/Qt/5.15.0/clang_64/lib/QtWebEngine.framework/Resources/QtWebEngine.prl \
		../../../Media/Qt/5.15.0/clang_64/lib/QtWebEngineCore.framework/Resources/QtWebEngineCore.prl \
		../../../Media/Qt/5.15.0/clang_64/lib/QtQuick.framework/Resources/QtQuick.prl \
		../../../Media/Qt/5.15.0/clang_64/lib/QtGui.framework/Resources/QtGui.prl \
		../../../Media/Qt/5.15.0/clang_64/lib/QtQmlModels.framework/Resources/QtQmlModels.prl \
		../../../Media/Qt/5.15.0/clang_64/lib/QtWebChannel.framework/Resources/QtWebChannel.prl \
		../../../Media/Qt/5.15.0/clang_64/lib/QtQml.framework/Resources/QtQml.prl \
		../../../Media/Qt/5.15.0/clang_64/lib/QtNetwork.framework/Resources/QtNetwork.prl \
		../../../Media/Qt/5.15.0/clang_64/lib/QtPositioning.framework/Resources/QtPositioning.prl \
		../../../Media/Qt/5.15.0/clang_64/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile NewsReader.pro -config release
../../../Media/Qt/5.15.0/clang_64/mkspecs/features/spec_pre.prf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/qdevice.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/features/device_config.prf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/common/unix.conf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/common/mac.conf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/common/macx.conf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/common/sanitize.conf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/common/gcc-base.conf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/common/clang.conf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/common/clang-mac.conf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/qconfig.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_pdf.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_pdf_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_pdfwidgets.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3d.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3d_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3dassetimport.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3drender.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3drender_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3druntimerender.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3dutils.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick3dutils_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Media/Qt/5.15.0/clang_64/mkspecs/features/qt_functions.prf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/features/qt_config.prf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Media/Qt/5.15.0/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/features/mac/sdk.prf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/features/toolchain.prf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/features/mac/toolchain.prf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/features/default_pre.prf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/features/resolve_config.prf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/features/default_post.prf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/features/mac/default_post.prf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/features/mac/mac.prf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/features/warn_on.prf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/features/qt.prf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/features/resources_functions.prf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/features/resources.prf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/features/moc.prf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/features/unix/opengl.prf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/features/unix/thread.prf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/features/qmake_use.prf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/features/file_copies.prf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/features/mac/rez.prf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/features/testcase_targets.prf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/features/exceptions.prf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/features/yacc.prf:
../../../Media/Qt/5.15.0/clang_64/mkspecs/features/lex.prf:
NewsReader.pro:
qml.qrc:
documentation.qrc:
images.qrc:
../../../Media/Qt/5.15.0/clang_64/lib/QtWebEngine.framework/Resources/QtWebEngine.prl:
../../../Media/Qt/5.15.0/clang_64/lib/QtWebEngineCore.framework/Resources/QtWebEngineCore.prl:
../../../Media/Qt/5.15.0/clang_64/lib/QtQuick.framework/Resources/QtQuick.prl:
../../../Media/Qt/5.15.0/clang_64/lib/QtGui.framework/Resources/QtGui.prl:
../../../Media/Qt/5.15.0/clang_64/lib/QtQmlModels.framework/Resources/QtQmlModels.prl:
../../../Media/Qt/5.15.0/clang_64/lib/QtWebChannel.framework/Resources/QtWebChannel.prl:
../../../Media/Qt/5.15.0/clang_64/lib/QtQml.framework/Resources/QtQml.prl:
../../../Media/Qt/5.15.0/clang_64/lib/QtNetwork.framework/Resources/QtNetwork.prl:
../../../Media/Qt/5.15.0/clang_64/lib/QtPositioning.framework/Resources/QtPositioning.prl:
../../../Media/Qt/5.15.0/clang_64/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile NewsReader.pro -config release

qmake_all: FORCE

NewsReader.app/Contents/PkgInfo: 
	@test -d NewsReader.app/Contents || mkdir -p NewsReader.app/Contents
	@$(DEL_FILE) NewsReader.app/Contents/PkgInfo
	@echo "APPL????" > NewsReader.app/Contents/PkgInfo
NewsReader.app/Contents/Resources/empty.lproj: 
	@test -d NewsReader.app/Contents/Resources || mkdir -p NewsReader.app/Contents/Resources
	@touch NewsReader.app/Contents/Resources/empty.lproj
	
NewsReader.app/Contents/Info.plist: 
	@test -d NewsReader.app/Contents || mkdir -p NewsReader.app/Contents
	@$(DEL_FILE) NewsReader.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.NewsReader,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.NewsReader,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.13,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,NewsReader,g" -e "s,@LIBRARY@,NewsReader,g" -e "s,\$${EXECUTABLE_NAME},NewsReader,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" ../../../Media/Qt/5.15.0/clang_64/mkspecs/macx-clang/Info.plist.app >NewsReader.app/Contents/Info.plist

all: Makefile \
		NewsReader.app/Contents/PkgInfo \
		NewsReader.app/Contents/Resources/empty.lproj \
		NewsReader.app/Contents/Info.plist NewsReader.app/Contents/MacOS/NewsReader

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc documentation.qrc images.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../../../Media/Qt/5.15.0/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents news.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp news.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r NewsReader.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -config release

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_qml.cpp qrc_documentation.cpp qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp qrc_documentation.cpp qrc_images.cpp
qrc_qml.cpp: qml.qrc \
		../../../Media/Qt/5.15.0/clang_64/bin/rcc \
		NewsWindowForm.ui.qml \
		NewsSplashForm.ui.qml \
		NewsWindow.qml \
		NewsSplash.qml \
		main.qml
	/Volumes/Media/Qt/5.15.0/clang_64/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

qrc_documentation.cpp: documentation.qrc \
		../../../Media/Qt/5.15.0/clang_64/bin/rcc \
		LICENSE \
		README.md
	/Volumes/Media/Qt/5.15.0/clang_64/bin/rcc -name documentation documentation.qrc -o qrc_documentation.cpp

qrc_images.cpp: images.qrc \
		../../../Media/Qt/5.15.0/clang_64/bin/rcc \
		newsapi.png
	/Volumes/Media/Qt/5.15.0/clang_64/bin/rcc -name images images.qrc -o qrc_images.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../Media/Qt/5.15.0/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wall -Wextra -dM -E -o moc_predefs.h ../../../Media/Qt/5.15.0/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_news.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_news.cpp
moc_news.cpp: news.h \
		../../../Media/Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Media/Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Media/Qt/5.15.0/clang_64/lib/QtQml.framework/Headers/QQmlContext \
		../../../Media/Qt/5.15.0/clang_64/lib/QtQml.framework/Headers/qqmlcontext.h \
		../../../Media/Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/QJsonArray \
		../../../Media/Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/qjsonarray.h \
		../../../Media/Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/QJsonObject \
		../../../Media/Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/qjsonobject.h \
		../../../Media/Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/QSettings \
		../../../Media/Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/qsettings.h \
		../../../Media/Qt/5.15.0/clang_64/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		../../../Media/Qt/5.15.0/clang_64/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		moc_predefs.h \
		../../../Media/Qt/5.15.0/clang_64/bin/moc
	/Volumes/Media/Qt/5.15.0/clang_64/bin/moc $(DEFINES) --include /Volumes/Projects/GitHub/NewsReader/moc_predefs.h -I/Volumes/Media/Qt/5.15.0/clang_64/mkspecs/macx-clang -I/Volumes/Projects/GitHub/NewsReader -I/Volumes/Media/Qt/5.15.0/clang_64/lib/QtWebEngine.framework/Headers -I/Volumes/Media/Qt/5.15.0/clang_64/lib/QtWebEngineCore.framework/Headers -I/Volumes/Media/Qt/5.15.0/clang_64/lib/QtQuick.framework/Headers -I/Volumes/Media/Qt/5.15.0/clang_64/lib/QtGui.framework/Headers -I/Volumes/Media/Qt/5.15.0/clang_64/lib/QtQmlModels.framework/Headers -I/Volumes/Media/Qt/5.15.0/clang_64/lib/QtWebChannel.framework/Headers -I/Volumes/Media/Qt/5.15.0/clang_64/lib/QtQml.framework/Headers -I/Volumes/Media/Qt/5.15.0/clang_64/lib/QtNetwork.framework/Headers -I/Volumes/Media/Qt/5.15.0/clang_64/lib/QtPositioning.framework/Headers -I/Volumes/Media/Qt/5.15.0/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.3/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Volumes/Media/Qt/5.15.0/clang_64/lib news.h -o moc_news.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../../../Media/Qt/5.15.0/clang_64/lib/QtGui.framework/Headers/QGuiApplication \
		../../../Media/Qt/5.15.0/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		../../../Media/Qt/5.15.0/clang_64/lib/QtQml.framework/Headers/QQmlApplicationEngine \
		../../../Media/Qt/5.15.0/clang_64/lib/QtQml.framework/Headers/qqmlapplicationengine.h \
		../../../Media/Qt/5.15.0/clang_64/lib/QtQml.framework/Headers/QQmlContext \
		../../../Media/Qt/5.15.0/clang_64/lib/QtQml.framework/Headers/qqmlcontext.h \
		../../../Media/Qt/5.15.0/clang_64/lib/QtWebEngine.framework/Headers/QtWebEngine \
		../../../Media/Qt/5.15.0/clang_64/lib/QtWebEngine.framework/Headers/qtwebengineglobal.h \
		../../../Media/Qt/5.15.0/clang_64/lib/QtWebEngine.framework/Headers/qquickwebengineprofile.h \
		../../../Media/Qt/5.15.0/clang_64/lib/QtWebEngine.framework/Headers/qquickwebenginescript.h \
		../../../Media/Qt/5.15.0/clang_64/lib/QtWebEngine.framework/Headers/qtwebengineversion.h \
		../../../Media/Qt/5.15.0/clang_64/lib/QtGui.framework/Headers/QFontDatabase \
		../../../Media/Qt/5.15.0/clang_64/lib/QtGui.framework/Headers/qfontdatabase.h \
		news.h \
		../../../Media/Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Media/Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Media/Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/QJsonArray \
		../../../Media/Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/qjsonarray.h \
		../../../Media/Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/QJsonObject \
		../../../Media/Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/qjsonobject.h \
		../../../Media/Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/QSettings \
		../../../Media/Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/qsettings.h \
		../../../Media/Qt/5.15.0/clang_64/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		../../../Media/Qt/5.15.0/clang_64/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

news.o: news.cpp ../../../Media/Qt/5.15.0/clang_64/lib/QtNetwork.framework/Headers/QNetworkReply \
		../../../Media/Qt/5.15.0/clang_64/lib/QtNetwork.framework/Headers/qnetworkreply.h \
		../../../Media/Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Media/Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Media/Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/QJsonObject \
		../../../Media/Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/qjsonobject.h \
		../../../Media/Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/QJsonArray \
		../../../Media/Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/qjsonarray.h \
		../../../Media/Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/QJsonDocument \
		../../../Media/Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/qjsondocument.h \
		../../../Media/Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/QFile \
		../../../Media/Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../../Media/Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/QTextCodec \
		../../../Media/Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/qtextcodec.h \
		../../../Media/Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../../../Media/Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		news.h \
		../../../Media/Qt/5.15.0/clang_64/lib/QtQml.framework/Headers/QQmlContext \
		../../../Media/Qt/5.15.0/clang_64/lib/QtQml.framework/Headers/qqmlcontext.h \
		../../../Media/Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/QSettings \
		../../../Media/Qt/5.15.0/clang_64/lib/QtCore.framework/Headers/qsettings.h \
		../../../Media/Qt/5.15.0/clang_64/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		../../../Media/Qt/5.15.0/clang_64/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o news.o news.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

qrc_documentation.o: qrc_documentation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_documentation.o qrc_documentation.cpp

qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_images.o qrc_images.cpp

moc_news.o: moc_news.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_news.o moc_news.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/NewsReader/bin || mkdir -p $(INSTALL_ROOT)/opt/NewsReader/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/NewsReader/bin/NewsReader.app
	
	$(QINSTALL) NewsReader.app $(INSTALL_ROOT)/opt/NewsReader/bin/NewsReader.app
	-$(STRIP) $(INSTALL_ROOT)/opt/NewsReader/bin/NewsReader.app/Contents/MacOS/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/NewsReader/bin/NewsReader.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/NewsReader/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

